EMFTeam/EMF

EMF/EMF_changelog.txt
EMF/events/emf_vanilla.txt
EMF/events/soa_jewish_events.txt
EMF/localisation/emf_vanilla.csv

Jewish councilor events now include an option to refuse, and if accepted they give appropriate sympathy traits and opinion modifiers so the prospective councilors are more useful

Adjusted Jewish councilor generation events

---

EMF+VEvents/common/on_actions/00_on_actions.txt
EMF/events/wol_intrigue_events.txt

Removed the opinion and rival bypasses from the personality check, but added lunatic and possessed (in keeping with the murder plot conditions)

Adjust AI weights for murder event

---

EMF/decisions/emf_prisoner_decisions.txt
EMF/localisation/emf_prisoner.csv

I improved the logic a tiny bit so it no longer charges you piety for executing folks of a different religion, which is consistent with the execute button's behavior. Also: the individual prisoner tooltips now indicate whether you will lose piety or gain Kinslayer, making it easier to tell which prisoner you might not want to execute.

Worked some tooltip magic on execute all decision

---

EMF/decisions/conversion_decisions.txt

Changed a couple of effects on the decision.
Changes about it:
*will only activate Orthodox Church if it's not already active.
*will only deactivate Iconoclast Church if it's already active.
Reason for change: it just appears on the tooltip, which is confusing in a case where the Orthodox Church is active or the Iconoclast isn't.

Changed renounce_iconoclasm decision

---

EMF/decisions/crown_laws.txt
EMF/decisions/emf_demesne_laws.txt
EMF/src/demesne_laws.pl

- Temporary titles (e.g., revolt titles) now no longer will have crown laws if of king- or empire-tier
- Temporary titles will now no longer have any of the non-vanilla demesne laws ([focus, obligations] x [feudal, burgher, clergy, iqta]) (they're not affected by liege levy laws during civil wars, if revolters, anyway)
- They'll still have the vanilla demesne laws which affect vassal limit, whether viceroyalties are enabled and what kind, etc. I figured that it might be dangerous to mess with these, but if so, their `allow` should also be locked to whatever initial value the title was given, ideally. Will worry about them some other time.

No [normal] laws for temporary titles

---

EMF/EMF_changelog.txt
EMF/events/emf_holy_orders.txt
EMF/localisation/emf_holy_orders.csv

Vanilla events can still form them earlier, but now they're guaranteed to show up eventually if reformation happens. (Someday the vanilla events should be fixed so they work properly on the SWMH map and so forth, but that's for another time...)

Allow Jomsvikings to form like other holy orders

---

EMF+SWMH/common/cb_types/00_imperial_reconquest.txt
EMF+SWMH/map/geographical_region.txt
EMF/common/cb_types/00_imperial_reconquest.txt
EMF/map/geographical_region.txt

swmh-integ is where we want to merge this, right?
There were a couple of differences in the EMF and EMF+SWMH versions of 00_imperial_reconquest.txt besides just the duchy lists, so I left them separate. DIff those two files together to see when I mean. Maybe they can be reduced to one like you mentioned was your intention, but I don't know how to do it.
Did I implement the CB-checking logic in the best way?
The regions have been tweaked in two ways since you last saw them (⇒ http://imgur.com/a/ndyfN).
- Vanilla regions have been added, more or less matching the SWMH regions.
- Each tier's region no longer includes the lesser tiers’ regions. The regions are mutually exclusive.
- I tweaked tiers 5 and 6 a little. The French–German border doesn’t mean much to a Roman Empire, so I moved (most …

Imperial Reconquest uses region system; tiers tweaked

---

EMF/EMF_changelog.txt
EMF/events/rebel_events_horse_lords.txt

These types of revolts-- and their reinforcements-- should no longer happen whenever any old provincial revolt happens if I understand `on_rebel_revolt` correctly, because they are now restricted to firing only upon nomadic provinces.

Untested fix of unnecessary vanilla bug RE: minor clan uprisings

---

EMF/EMF_changelog.txt
EMF/events/emf_empires.txt

- Exempt `e_seljuk_turks` from AED (only until AED is upgraded to only demote empires after a dynamically-timed delay since fulfilling the demotion conditions).
- When demoting to a new kingdom title, copy the laws from the old empire-tier title first.
- Do not use the `unsafe_` version of `destroy_landed_title` for now (too many crazy landless & other weird empire-tier titles at this time, needs sorting-out)

AED: Protect e_seljuk_turks & copy_title_laws on kingdom-demotion

---

EMF+ArkoCoA/common/religions/ArkoCoA_religions.txt

ARKOpack takes care of its own folderized 00_religions.txt override now.

EMF+ArkoCoA module obsolete

---

EMF/EMF_changelog.txt
EMF/common/objectives/00_factions.txt

- Elective faction has been significantly nerfed now. Hope this is neither too much nor too little.
- @escalonn: I checked the CB for the elective faction, and if the title whose succession law is in question is already / becomes an elective monarchy, the revolt immediately invalidates, so I don't know what you were seeing in That One Observe.

Elective monarchy faction nerfs & improved logic

---

EMF+SWMH/history/characters/hungarian.txt
EMF+Vanilla/history/characters/hungarian.txt
EMF/EMF_changelog.txt
EMF/common/minor_titles/00_minor_titles.txt

- Rebalanced 867 starting troops of Magyars for both vanilla and SWMH maps
- Fixed issue where `title_commander`'s `allowed_to_hold` was vanilla rather than EMF's command eligibility conditions (`job_marshal`'s `allow`)

Magyar starting troops & Commander minor title

---

EMF/EMF_changelog.txt
EMF/events/emf_nomad.txt

Now, the only nomadic/empty provinces that will be retained by a nomad settling as feudal are ones that are directly-connected to the new, non-nomadic realm. This reduces a lot of potential border gore.

Nomad settlement improvement

---

EMF/events/PB_startup_2.txt
EMF/events/emf_startup.txt

... not really a loop so much as excessive invocation.
I'm not really sure what changed in 2.4 to cause this, but it appears like it should've always happened (yet did not).

Fix for Baqt "infinite loop"

---

EMF/events/rebel_events_the_old_gods.txt

All of the vanilla TOG rebel spawns (esp. the nationalist rebels) are now `cannot_inherit=yes` and `disband_on_peace=yes`.
The nationalist rebels *exactly* match the troop compositions of the event troop subunits of all sampled characters with ghost armies so far, and all other properties match.

Probable solution to event troop ghost armies

---

EMF/EMF_changelog.txt
EMF/common/cb_types/29_imperial_reconquest.txt

... a little enhancement that's saved me some trouble in my Kezrüm playthrough.
This only matters when attacking king- or emperor-tier top lieges with the CB, and it wasn't possible to do correctly before patch 2.3.

Imperial Reconquest CB more friendly to viceroyalties

---

EMF/EMF_changelog.txt
EMF/common/opinion_modifiers/00_opinion_modifiers.txt

Apparently the opinion modifier magnitude was accidentally doubled somewhere during the 2.4 compatibility patch process.  This probably explains increased Elective Monarchy faction activity, as that faction requires zero CA on the title, and it would be relatively more difficult for the AI to get away with a CA increase with twice the 10-year opinion malus.

Fixed doubled opinion malus for increasing crown authority

---

EMF/common/on_actions/emf_on_actions.txt
EMF/decisions/emf_settlement_decisions.txt
EMF/decisions/settlement_decisions.txt
EMF/events/emf_nomad.txt
EMF/localisation/emf_core.csv
EMF/localisation/emf_nomad.csv

- `on_new_holder_usurpation` catch-all to help enforce the new "leave behind a tribe if different culture" rule
- various vanilla fixes to `pillage_settlement`
- added an `emf_convert_tribal_to_temple` settlement decision for theocracies
- `pillage_settlement` "tooltip" (effects printed into a diplo-action window) is now much more concise & smart and should actually fit in the window
- when AI is using `pillage_settlement`, it will never actually destroy the last settlement in a different-culture province
- magyars won't pillage anything inside de jure `k_hungary`, since that's about to be their damn home
- made conditions for tribal settlement conversion (for non-tribals) require either the appropriate maxed-out building for their type OR 100 gold
- tribal settlement conversion no longer …

Nomad, tribal, and theocracy stuff

---

EMF/common/scripted_effects/emf_nomad_effects.txt
EMF/events/emf_nomad.txt

Case should never actually happen, but if for some reason it did, it may have CTDed.  Now, it won't.

bugfix for nomad settlement that might _theoretically_ prevent a CTD

---

EMF/emf_obj_increase_demesne.txt
EMF/interface/EMF_objectives.gfx
EMF/localisation/emf_objectives.csv

@thefinestsieve They should presumably all use the same icon.  Currently, they're using the 'Amass Wealth' generic icon as a placeholder.
Added an 'Increase Size of Demesne' ambition for demesne sizes 1 through 12.  Player can repeat, but the AI cannot, and the AI can't access the top 3 tiers of the ambition.

12 Tiered 'Increase Size of Demense' Ambitions

---

EMF/common/cb_types/03_claim_on_liege.txt
EMF/common/cb_types/04_claim_on_liege_plot.txt
EMF/common/cb_types/06_other_claim_on_liege.txt
EMF/common/cb_types/08_change_seniority_succession_law.txt
EMF/common/cb_types/09_change_primogeniture_succession_law.txt
EMF/common/cb_types/10_change_feudal_elective_succession_law.txt
EMF/common/cb_types/18_overthrow_ruler.txt
EMF/common/cb_types/20_change_gavelkind_succession_law.txt
EMF/common/cb_types/22_lower_tribal_organization_law.txt
EMF/common/cb_types/28_cb_faction_independence.txt
EMF/common/cb_types/49_cb_install_antiking.txt
EMF/common/cb_types/57_cb_install_khan.txt
EMF/common/scripted_effects/emf_cb_effects.txt
EMF/events/emf_dynlevy.txt
EMF/localisation/emf_cb.csv

- Fixed dynlevy helper (readjust dynlevy laws due to realm fracture) for 3rd-party major revolt CBs (other_claim_on_liege)
- Rolled dynlevy helpers into scripted_effects and applied them everywhere
- Added `on_invalidation` handlers for fixing dynlevy state immediately upon revolt invalidation
- Added support in the independence faction CB for non-independent lieges (faction will need to be adjusted to support that-- finally!)
- Gradual move to scripted effects for defeat/victory helpers (re: war ambitions)

Major revolt CB maintenance

---

EMF/common/laws/emf_demesne_laws.txt
EMF/common/on_actions/emf_on_actions.txt
EMF/common/opinion_modifiers/emf_laws_opinion_modifiers.txt
EMF/events/emf_laws.txt
EMF/localisation/zz~emf_laws.csv

... but free duchy revocation instead, until the imperial government form and viceroy replacement system which @Rylock is currently designing is ready for us to begin collaboration. Succession laws still support viceroyalties (though I will eventually remove that later), so this will still work w/ existing saves without much disruption.

No mo' viceroyalties
