EMF/common/landed_titles/landed_titles.txt
EMF/events/cm_religious_events.txt
EMF/events/emf_holy_orders.txt
EMF/events/imprisoned_events.txt
EMF/events/oldgods_mongol_events.txt
EMF/events/soa_heresy_events.txt
EMF/events/soa_holy_order_events.txt
EMF/events/soa_jewish_events.txt
EMF/history/characters/turkish.txt

Fixed vanilla encoding errors in EMF

---

EMF/events/wol_intrigue_events.txt

Feel free to take a glance over it. I might have missed something.

Intrigue focus AI weight adjustment

---

EMF/decisions/conversion_decisions.txt
EMF/decisions/emf_misc_decisions.txt
EMF/decisions/holy_order_decisions.txt
EMF/decisions/minor_decisions.txt
EMF/localisation/emf_vanilla.csv

I added my new versions of the feast, fair, and hunt decisions (which seem to work very well) and also imported all the remaining vanilla decision files which PB modified. (In keeping with my new approach, I'll add the changelog update in my subsequent pull request.)

Decision updates

---

EMF/events/PB_various.txt

This will get the decisions working properly even without PB.

Import PB_various.txt

---

EMF/decisions/emf_prisoner_decisions.txt
EMF/events/emf_prisoners.txt
EMF/localisation/emf_prisoners.csv

You can ignore the notes in the prisoner files. I'll clean all of them out once I get the other prisoner decisions and events properly rewritten.

Last bit of prisoner handling updates

---

EMF/events/imprisoned_events.txt

AI can now beg players, but only after they've been in prison for ten years.

Minor accommodation begging adjustment

---

EMF/decisions/realm_decisions.txt
EMF/events/PB_various.txt
EMF/events/emf_feudalizer.txt

I'm sure you will anyway, but definitely take a glance over these. I'm still not entirely at home with the title/law end of the things.

Removed a few stray emperor_peace references

---

EMF+VEvents/common/on_actions/00_on_actions.txt
EMF/common/event_modifiers/emf_siege_modifiers.txt
EMF/common/on_actions/00_on_actions.txt
EMF/decisions/dynasty_decisions.txt
EMF/decisions/emf_prisoner_decisions.txt
EMF/decisions/emf_siege_decisions.txt
EMF/events/emf_prisoner.txt
EMF/events/emf_siege.txt
EMF/localisation/emf_siege.csv

Siege Module

---

EMF/EMF_changelog.txt
EMF/decisions/CatholicSchism.txt
EMF/events/CatholicSchism.txt

I also made some minor changes to its functionality, which I tested successfully

Imported Catholic Schism module from PB

---

EMF+SWMH/common/cultures/00_cultures.txt
EMF/common/buildings/00_CastleCulture.txt
EMF/localisation/emf_lucky.csv

Also caught a couple other minor errors while on the hunt.

Clear up mistakes in my SWMH compatibility

---

EMF/common/traits/00_traits.txt
EMF/common/traits/01_traits.txt
EMF/common/traits/02_traits.txt
EMF/decisions/PB_loans.txt
EMF/decisions/PB_marriage.txt
EMF/decisions/PB_war_checks_IR.txt
EMF/localisation/emf_holy_orders.csv

I also added comments and reordered some things so they'll be slightly easier to merge in the future. Also: What is the point of the marriage decisions? Does anyone use them? I know I never have.

Brought over remaining PB decisions and PB's version of vanilla trait files

---

EMF/common/retinue_subunits/00_retinue_subunits.txt

Also take it away from the Lombards, who have their own retinue

Give SWMH Italians their retinues back

---

EMF/EMF_changelog.txt
EMF/common/combat_tactics.txt
EMF/src/combat_tactics.csv

Fixed a typo that caused stand fast tactics to not be properly vulnerable

Typo in combat tactics

---

EMF/EMF_changelog.txt
EMF/events/emf_siege.txt

Also included a minor cosmetic change

Fix Siege module bug

---

EMF/events/emf_vanilla.txt
EMF/events/job_lord_spiritual.txt

If we are eventually planning on rewriting all the councilor events, maybe we should go ahead and create a new emf_council module for it?

Fixed a couple action_build_zeal glitches

---

EMF/events/emf_siege.txt
EMF/localisation/emf_buildings.csv
EMF/localisation/emf_cultures.csv
EMF/localisation/emf_holy_orders.csv
EMF/localisation/emf_lucky.csv
EMF/localisation/emf_prisoner.csv
EMF/localisation/emf_regional.csv
EMF/localisation/emf_siege.csv
EMF/localisation/emf_vanilla.csv

Also (sort of embarrassing) localization cleanup

Updated siege timer

---

EMF/localisation/emf_nwo.csv

Quickly scanned through EMF localisations, didn’t see any other file with the problem.

fix emf_nwo.csv encoding, utf8->cp1252

---

EMF+SWMH/common/defines.lua
EMF+SWMH/common/static_modifiers.txt
EMF/localisation/emf_core.csv

I guess the PR git changelog wasn't wrong. I just have NO clue why these changed. None of the commits from my branch touched them, but they changed anyway. Also: Fixing a minor conflict merge error.

Restore messed up EMF+SWMH values

---

EMF+SWMH/common/defines.lua
EMF+SWMH/common/static_modifiers.txt
EMF+SWMH/events/emf_hre_map.txt
EMF+SWMH/events/emf_startup_map.txt
EMF/EMF_changelog.txt
EMF/localisation/emf_core.csv

Still have a Frankish HRE to add at some point, but I'm not in a big hurry, as it should rightfully be a difficult path and thus almost never achieved by the AI (and thus would require an 867 Catholic player to care).  Nevertheless, with the release of SWMH3, we will have a lot more interest in the German and Dutch areas again, so it's not getting tossed off the menu.

Finished initial HRE solution

---

EMF/decisions/conversion_decisions.txt
EMF/decisions/councillor_decision.txt
EMF/decisions/dynasty_decisions.txt
EMF/decisions/emf_prisoner_decisions.txt
EMF/decisions/faction_decisions.txt
EMF/decisions/holy_order_decisions.txt
EMF/decisions/minor_decisions.txt
EMF/decisions/realm_decisions.txt
EMF/decisions/unit_decisions.txt
EMF/decisions/vassal_decisions.txt
EMF/decisions/way_of_life_decisions.txt

@zijistark - There's a couple of things that need extra attention here, including realm decisions (particularly the hungary stuff and tribal decisions) and they've moved the laws to the common folder. I'll probably leave the law stuff to you.

Yet more 2.4 compatch stuff

---

EMF/common/opinion_modifiers/duel_engine.txt
EMF/common/opinion_modifiers/emf_core_opinion_modifiers.txt
EMF/interface/EMF_objectives.gfx
EMF/interface/EMF_traits.gfx
EMF/interface/eventwindow_duelengine.gfx
EMF/interface/traits_duel_engine.gfx

@zijistark This should be everything that was missing, save localization. I'm still trying to decide whether we should just keep using PB's localization (and nothing else) so it'll be easier to later on only import the localization we actually use (because the validator can make a nice list for us), or whether to just toss it all in and cut it down later. It's up to you, really, but I personally prefer the former plan unless you've got another idea.

Import some missing PB elements

---

EMF/events/emf_crier.txt

Silly nomads coming in and breaking everything

Crier 2.4 update

---

EMF+SWMH/common/cultures/00_cultures.txt

Does EMF+SWMH need its own identical copy of 00_cultures.txt?

mande culture fix from swmh

---

EMF/common/cb_types/62_nomad_invasion.txt

Fix for extra closing bracket in nomad_invasion

---

EMF+SWMH/common/defines.txt
EMF/events/emf_empires.txt

- Conqueror trait is more liberally applied (notably, mongol invaders don't need to stay Tengri so long as they're nomadic)
- EMF+SWMH disallows starting upon dates after 1205.1.1

Few tweaks

---

EMF/EMF_changelog.txt
EMF/events/emf_crier.txt

Crier fix for Mongol Empire

---

EMF+SWMH/common/bookmarks/00_bookmarks.txt

- Repurpose `BM_THE_MONGOLS` in place of `BM_JERUSALEM`
- Repurpose `BM_100_YEARS_WAR` in place of `BM_THE_LATIN_EMPIRE`

Update for new era bookmarks in SWMH

---

EMF+ArkoInterface/interface/province.gfx

- Only touches `interface/province.gfx`

Added EMF+ArkoInterface compatch module

---

EMF+SWMH/map/geographical_region.txt

Really wish this file were folderized. Almost tempted to generate it on-demand from the SWMH base file with the installer.

(EMF+SWMH) Merged latest SWMH region definitions

---

EMF/EMF_changelog.txt
EMF/events/wol_theology_events.txt

If I got the percentages wrong it's because I'm tired.

NERF THE HERETICS

---

EMF+SWMH/map/geographical_region.txt

merged more region changes from SWMH

---

EMF/common/cb_types/emf_horde_invasion.txt
EMF/events/emf_empires.txt
EMF/events/mongol_events.txt
EMF/localisation/emf_empires.csv
EMF/map/geographical_region.txt

Barring any blatant errors which might arise during more testing, this should be the last of the "pillage-burn" guided Mongol invasion code.

More improvements to pillage-burn & vanilla map adaptation

---

EMF/EMF_changelog.txt
EMF/decisions/settlement_decisions.txt

... and earmarked them for future debugging, if relevant.

Nerf to settlement-spawned event troops (/3)

---

EMF/common/objectives/00_factions.txt

Extra bracket inside faction_succ_feudal_elective!

---

EMF+SWMH/map/geographical_region.txt

Swear to God, I'm going to automate this somehow.

yet another update to EMF+SWMH regions file

---

EMF+SWMH/events/mongol_events.txt
EMF+Vanilla/events/mongol_events.txt
EMF/EMF_changelog.txt
EMF/common/scripted_triggers/emf_empires_triggers.txt
EMF/events/emf_empires.txt
EMF/events/vassal_request_events.txt

- Fixes for "Sky Lords" issue
- Pillage-burn respects alliances
- If a ruler exceeds their VL upon succession, players are exempt from the new "can only lose border vassals" rule

Mongol stuff (mostly)

---

EMF/EMF_changelog.txt
EMF/events/PB_historical.txt

go Rum go!

---

EMF/common/event_modifiers/emf_lucky_ruler_modifiers.txt
EMF/common/retinue_subunits/00_retinue_subunits.txt
EMF/common/retinue_subunits/01_retinue_subunits_swmh.txt
EMF/common/scripted_triggers/emf_core_retinue_hire_trigger.txt

- Moved my "retinue spam filter" conditions to a scripted_trigger
- Made an exception to the spam filter for all patricians
- Added Turkmen cultural retinue
- Tweaked more non-feudal-related lucky ruler modifiers

Revamped retinue hire triggers & added Turkmen cultural retinue

---

EMF+SWMH/common/static_modifiers.txt
EMF/EMF_changelog.txt
EMF/common/static_modifiers.txt

old and very_old reduced in health severity

---

EMF/common/event_modifiers/emf_core_modifiers.txt
EMF/common/objectives/emf_obj_become_duke.txt
EMF/common/objectives/emf_obj_become_emperor.txt
EMF/common/objectives/emf_obj_become_superduke.txt
EMF/common/objectives/emf_obj_independence.txt
EMF/interface/EMF_objectives.gfx
EMF/localisation/emf_objectives.csv

- _Become Independent_
- _Become Duke_
- _Become a Super-Duke_
- _Become Emperor_
@thefinestsieve These ambitions are currently using the 'Pledge Peace' ambition's icon as a placeholder until you can work your magic.

Added 4 ambitions, adapted from Plus

---

EMF/common/objectives/emf_obj_fifteen_children.txt
EMF/common/objectives/emf_obj_five_children.txt
EMF/common/objectives/emf_obj_ten_children.txt
EMF/common/objectives/emf_obj_twenty_children.txt
EMF/interface/EMF_objectives.gfx
EMF/localisation/emf_objectives.csv

@thefinestsieve Four more ambition icons upon which your icon skills can chomp! I imagine these won't be as interesting per icon as the last 4, as with any tiered sort of ambition.  Again, they're just holding the 'Pledge Peace' ambition icon as a placeholder for now.
Added these ambitions, adapted from CK2+:
- *"Have Five Children"*
- *"Have Ten Children"*
- *"Have Fifteen Children"*
- *"Have Twenty Children"*

4 More Ambitions

---

EMF/common/objectives/emf_obj_civilize_province.txt
EMF/events/PB_culture.txt
EMF/events/emf_ambitions.txt
EMF/events/job_lord_spiritual.txt
EMF/events/job_steward.txt
EMF/interface/EMF_objectives.gfx
EMF/localisation/emf_objectives.csv

@thefinestsieve Another icon!
This ambition ought to make Meneth roll over in his modding grave...
I don't currently support ambition success via any province culture change caused by SWMH's own melting pot events. Mainly, I still need to fix those up before I go overriding them in EMF and adding to them.

Cultural/religious conv. fixes/tweaks & added "Change Province Culture" ambition
